# Generated by Django 3.0.5 on 2020-04-27 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('asal', models.CharField(max_length=50)),
                ('kontak', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('tahun', models.CharField(max_length=50)),
                ('penerbit', models.CharField(max_length=50)),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAPI.Penulis')),
            ],
        ),
    ]
